services:
  # Frontend (React/Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5000
      - REACT_APP_WS_URL=ws://localhost:5000
      - REACT_APP_STRIPE_PUBLISHABLE_KEY=pk_test_51234567890abcdef
      - REACT_APP_GA4_MEASUREMENT_ID=G-XXXXXXXXXX
      - REACT_APP_GTM_ID=GTM-XXXXXXX
      - REACT_APP_CDN_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - icepaca-dev
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Backend (Node.js/Express)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
      - "9229:9229"  # Debug port
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=mongodb://mongodb:27017/icepaca-dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - SESSION_SECRET=dev-session-secret-change-in-production
      - STRIPE_SECRET_KEY=sk_test_51234567890abcdef
      - STRIPE_WEBHOOK_SECRET=whsec_test_1234567890abcdef
      - EMAIL_SERVICE=gmail
      - EMAIL_USER=dev@icepaca.com
      - EMAIL_PASS=dev-email-password
      - CLOUDINARY_CLOUD_NAME=icepaca-dev
      - CLOUDINARY_API_KEY=123456789012345
      - CLOUDINARY_API_SECRET=dev-cloudinary-secret
      - BACKUP_ENABLED=false
      - ANALYTICS_ENABLED=false
      - DEBUG=icepaca:*
    depends_on:
      - mongodb
      - redis
    networks:
      - icepaca-dev
    restart: unless-stopped
    command: npm run dev

  # Database (MongoDB)
  mongodb:
    image: mongo:7
    container_name: icepaca-mongodb-dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=dev-password
      - MONGO_INITDB_DATABASE=icepaca-dev
    volumes:
      - mongodb_data:/data/db
      - ./scripts/db-init:/docker-entrypoint-initdb.d:ro
    networks:
      - icepaca-dev
    restart: unless-stopped

  # Redis (Caching & Sessions)
  redis:
    image: redis:7-alpine
    container_name: icepaca-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - icepaca-dev
    restart: unless-stopped

  # Blockchain Node (Simplified)
  blockchain:
    build:
      context: ./blockchain
      dockerfile: Dockerfile.dev
    container_name: icepaca-blockchain-dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - BLOCKCHAIN_PORT=3002
      - GENESIS_DIFFICULTY=4
    volumes:
      - ./blockchain:/app
      - blockchain_data:/app/data
    networks:
      - icepaca-dev
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local
  blockchain_data:
    driver: local

networks:
  icepaca-dev:
    driver: bridge